### ISSUE TITLE
stops at around 400 videos

### ISSUE THREAD

**Issue by clankie83** [Karim-Arab/Bulk-Tiktoks-Downloader#10]
my account has 600 vids...any ideas? I tried 3 times just to be sure. Thanks!

**Comment by Karim-Arab** [comment]
seems links stored in ram and that it limit , script is very simple to have db to store links not many have that much of videos :)

**Comment by Karim-Arab** [comment]
well links is stored in array and value is stored in variables  which is limited characters

**Comment by Karim-Arab** [comment]
try out [this](https://github.com/Karim-Arab/tiktok-downloader) it has more options
