### ISSUE TITLE
Please fix this problem

### ISSUE THREAD

**Issue by daltonjames777** [Karim-Arab/Bulk-Tiktoks-Downloader#17]
it stays for 20 min in the status--now is downloading x video-descriptions savet, and does not start downloading videos, please can you fix this
![121234122](https://user-images.githubusercontent.com/115239529/194559581-ac42f457-8aa3-48e1-8d79-4357872a7e5f.PNG)

**Comment by 941que** [comment]
I'm having the same issue it saves the description but not any of the videos (it does make a folder for the user too though)

**Comment by Karim-Arab** [comment]
fixed until i makes a new API project
